name: Update Playlist

on:
  schedule:
    - cron: '0 */6 * * *' # Wakes up and runs every 6 hours
  workflow_dispatch: # Allows you to trigger it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Merge Script
        run: python merge.py
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add master.m3u
          git commit -m "Auto-update master playlist" || exit 0
          git push
